---
git:
  depth: 1
language: node_js
node_js:
  - '0.12'
env:
  global:
    - COVERAGE=false
matrix:
  include:
    - node_js: "0.12"
      env: COVERAGE=true
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm i -g npm
  - npm i -g karma-cli jspm codeclimate-test-reporter
  - jspm config registries.github.auth $JSPM_GITHUB_TOKEN
  - jspm i
  - jspm i --dev
  - git checkout -- .
after_script:
 - "[ $COVERAGE == false ] || npm run test -- -- --coverage"
 - "[ $COVERAGE == false ] || codeclimate < coverage/report-lcov/lcov.info"
